apiVersion: apps/v1
kind: Deployment
metadata:
  name: languages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: languages
  template:
    metadata:
      labels:
        app: languages
    spec:
      containers:
      - image: okteto.dev/languages:latest
        name: languages
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3b9d5fc4-ce05-4839-a958-724dfed410b4"
        - name: Vless_Path
          value: "/vloygungh"
        - name: Vmess_UUID
          value: "3b9d5fc4-ce05-4839-a958-724dfed410b4"
        - name: Vmess_Path
          value: "/vmgsvstys"
        - name: Share_Path
          value: "/v2link"
